name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I've also considered...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area does this feature belong to?
      options:
        - Authentication/Security
        - Trading Strategy
        - Risk Management
        - User Interface
        - Charts/Visualization
        - Backtesting
        - API/Integration
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Can't use the app without it)
        - High (Would significantly improve my workflow)
        - Medium (Nice to have)
        - Low (Minor improvement)
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case for this feature
      placeholder: |
        As a trader, I need to...
        So that I can...
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Expected Benefits
      description: What benefits would this feature provide?
      placeholder: |
        - Improved performance
        - Better user experience
        - More trading strategies
        - etc.

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have any ideas on how this could be implemented? (Optional)
      placeholder: |
        This could be implemented by...
        We might need to add...

  - type: textarea
    id: examples
    attributes:
      label: Examples/References
      description: Are there any other tools or platforms that have this feature?
      placeholder: |
        - TradingView has a similar feature...
        - Binance implements this as...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Diagrams
      description: If applicable, add mockups, diagrams, or screenshots to help explain your feature
      placeholder: Drag and drop images here

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and feature requests
          required: true
        - label: This feature aligns with the project's goals
          required: false
        - label: I am willing to contribute to implementing this feature
          required: false
